package edu.ncsu.csc316.social.manager;

import static org.junit.jupiter.api.Assertions.*;

import java.io.FileNotFoundException;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * This test class tests the report manager methods and the reports generated
 * It tests that the string generated are in correct order and the alternative
 * flows that can occur
 * @author Chloe Coursey
 *
 */
class ReportManagerTest {

	/** A report manager with two non-empty files*/
	private ReportManager rm;
	
	/** a report manager with an empty people file */
	private ReportManager rm2;
	
	/** a report manager with an empty conneciton file */
	private ReportManager rm3;
	
	/**a valid file of people objects */
	private static final String PEOPLE_FILE = "input/people1.txt";
	
	/** a valid file of connection objects */
	private static final String CONNECTION_FILE = "input/valid_connections.txt";
	
	
	/**
	 * This method tests alternate flows such as a people file with no people
	 * in the file and a connection file with no connections within the file
	 */
	@Test 
	public void testAltFlowsConnectionsByPerson() {
		try {
			rm2 = new ReportManager("input/nopeople.txt", CONNECTION_FILE);
			assertEquals("No people information was provided.", rm2.getConnectionsByPerson());
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		try {
			rm3 = new ReportManager(PEOPLE_FILE, "input/noconnections.txt");
			assertEquals("No connections exist in the social media network.", rm3.getConnectionsByPerson());
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * This method sets up a report manager for each test
	 */
	@BeforeEach
	public void setUp() {
		try {
			rm = new ReportManager(PEOPLE_FILE, CONNECTION_FILE);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		
	}
	
	/**
	 * Tests the report generated by the connectionsByPerson method
	 */
	@Test
	public void testConnectionsByPerson() {
		assertEquals("Connections for Bennedict Cornfield (BCornfield654) {\n"
				+ "   Catherine Candid (CCandid123) on Twitter since Mon Feb 10 09:45:13 EST 2020" 
				+ "\n   Ralph Goodmann (RGoodmann23) on Instagram since Mon Feb 05 12:42:00 EST 2018"
				+ "\n   Ralph Goodmann (RGoodmann23) on Telegram since Sun Aug 05 04:42:00 EDT 2018\n}\n"
				
				
				+ "Connections for Catherine Candid (CCandid123) {\n"
				+ "   Bennedict Cornfield (BCornfield654) on Twitter since Mon Feb 10 09:45:13 EST 2020"
				+ "\n   Ralph Goodmann (RGoodmann23) on Instagram since Wed Jan 09 04:40:00 EST 2019"
				+ "\n   Ralph Goodmann (RGoodmann45) on Twitch since Fri Nov 13 12:32:00 EST 2020"
				+ "\n   Patty Smith (PSmith4567) on Facebook since Thu Jan 10 14:14:14 EST 2019\n}\n"
				
				
				+ "Connections for Garfield Smith (GSmith123456) {\n"
				+ "   Ralph Goodmann (RGoodmann23) on Instagram since Sun May 19 00:21:43 EDT 2019"
				+ "\n   Ralph Goodmann (RGoodmann45) on Twitch since Wed May 17 18:20:21 EDT 2017"
				+ "\n   Patty Smith (PSmith4567) on Instagram since Tue Aug 21 21:00:00 EDT 2018"
				+ "\n   Patty Smith (PSmith4567) on LinkedIn since Wed Aug 12 21:00:00 EDT 2020\n}\n"
				
				+ "Connections for Jeremy Renner (JRenner987) {\n"
				+ "   Ralph Goodmann (RGoodmann23) on Facebook since Thu Oct 11 05:04:39 EDT 2018"
				+ "\n   Ralph Goodmann (RGoodmann45) on Facebook since Sun Jun 11 05:04:39 EDT 2017\n}\n"

				
				
				+ "Connections for Matthew Madrid (MMadrid45) {\n"
				+ "   No connections exist\n}\n"
				
				
				+ "Connections for Patty Smith (PSmith4567) {\n"
				+ "   Catherine Candid (CCandid123) on Facebook since Thu Jan 10 14:14:14 EST 2019"
				+ "\n   Ralph Goodmann (RGoodmann45) on Twitter since Mon Feb 10 10:35:00 EST 2020"
				+ "\n   Garfield Smith (GSmith123456) on Instagram since Tue Aug 21 21:00:00 EDT 2018"
				+ "\n   Garfield Smith (GSmith123456) on LinkedIn since Wed Aug 12 21:00:00 EDT 2020\n}\n"
				
				
				+ "Connections for Ralph Goodmann (RGoodmann23) {\n"
				+ "   Catherine Candid (CCandid123) on Instagram since Wed Jan 09 04:40:00 EST 2019"
				+ "\n   Bennedict Cornfield (BCornfield654) on Instagram since Mon Feb 05 12:42:00 EST 2018"
				+ "\n   Bennedict Cornfield (BCornfield654) on Telegram since Sun Aug 05 04:42:00 EDT 2018"
				+ "\n   Ralph Goodmann (RGoodmann45) on LinkedIn since Fri Oct 13 12:12:00 EDT 2017"
				+ "\n   Jeremy Renner (JRenner987) on Facebook since Thu Oct 11 05:04:39 EDT 2018"
				+ "\n   Garfield Smith (GSmith123456) on Instagram since Sun May 19 00:21:43 EDT 2019\n}\n"
				
				
				+ "Connections for Ralph Goodmann (RGoodmann45) {\n"
				+ "   Catherine Candid (CCandid123) on Twitch since Fri Nov 13 12:32:00 EST 2020"
				+ "\n   Ralph Goodmann (RGoodmann23) on LinkedIn since Fri Oct 13 12:12:00 EDT 2017"
				+ "\n   Jeremy Renner (JRenner987) on Facebook since Sun Jun 11 05:04:39 EDT 2017"
				+ "\n   Garfield Smith (GSmith123456) on Twitch since Wed May 17 18:20:21 EDT 2017"
				+ "\n   Patty Smith (PSmith4567) on Twitter since Mon Feb 10 10:35:00 EST 2020\n}\n"

				, rm.getConnectionsByPerson());

				
	}
	
	/**
	 * Tests the report generated by the connectionsByPlatform method
	 */
	@Test
	public void testConnectionsByPlatform() {
		assertEquals("Connections on Facebook {\n"
				+ "   Sun Jun 11 05:04:39 EDT 2017: Ralph Goodmann (RGoodmann45) <--> Jeremy Renner (JRenner987)\n"
				+ "   Thu Oct 11 05:04:39 EDT 2018: Ralph Goodmann (RGoodmann23) <--> Jeremy Renner (JRenner987)\n"
				+ "   Thu Jan 10 14:14:14 EST 2019: Catherine Candid (CCandid123) <--> Patty Smith (PSmith4567)\n}\n"
				
				+ "Connections on Instagram {\n"
				+ "   Mon Feb 05 12:42:00 EST 2018: Bennedict Cornfield (BCornfield654) <--> Ralph Goodmann (RGoodmann23)\n"
				+ "   Tue Aug 21 21:00:00 EDT 2018: Garfield Smith (GSmith123456) <--> Patty Smith (PSmith4567)\n"
				+ "   Wed Jan 09 04:40:00 EST 2019: Catherine Candid (CCandid123) <--> Ralph Goodmann (RGoodmann23)\n"
				+ "   Sun May 19 00:21:43 EDT 2019: Ralph Goodmann (RGoodmann23) <--> Garfield Smith (GSmith123456)\n}\n"
				
				
				+ "Connections on LinkedIn {\n"
				+ "   Fri Oct 13 12:12:00 EDT 2017: Ralph Goodmann (RGoodmann23) <--> Ralph Goodmann (RGoodmann45)\n"
				+ "   Wed Aug 12 21:00:00 EDT 2020: Garfield Smith (GSmith123456) <--> Patty Smith (PSmith4567)\n}\n"
				
				
				+ "Connections on Telegram {\n"
				+ "   Sun Aug 05 04:42:00 EDT 2018: Bennedict Cornfield (BCornfield654) <--> Ralph Goodmann (RGoodmann23)\n}\n"
				+ ""
				+ "Connections on Twitch {\n"
				+ "   Wed May 17 18:20:21 EDT 2017: Ralph Goodmann (RGoodmann45) <--> Garfield Smith (GSmith123456)\n"
				+ "   Fri Nov 13 12:32:00 EST 2020: Catherine Candid (CCandid123) <--> Ralph Goodmann (RGoodmann45)\n}\n"
				
				
				+ "Connections on Twitter {\n"
				+ "   Mon Feb 10 09:45:13 EST 2020: Catherine Candid (CCandid123) <--> Bennedict Cornfield (BCornfield654)\n"
				+ "   Mon Feb 10 10:35:00 EST 2020: Ralph Goodmann (RGoodmann45) <--> Patty Smith (PSmith4567)\n}\n"
				
				
				, rm.getConnectionsByPlatform());
	}
	
	/**
	 * Tests the alternate flow of the connectionsByPlatform method with a people file
	 * that does not have any people in it and a connections file which is empty
	 */
	@Test 
	public void testAltFlowsConnectionsByPlatform() {
		try {
			rm2 = new ReportManager("input/nopeople.txt", CONNECTION_FILE);
			assertEquals("No people information was provided.", rm2.getConnectionsByPlatform());
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		try {
			rm3 = new ReportManager(PEOPLE_FILE, "input/noconnections.txt");
			assertEquals("No connections exist in the social media network.", rm3.getConnectionsByPlatform());
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
}
